=== yoshikun/Mobile/Test/Resources/data/Addiction.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by blue (yi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Addiction">
		<xs:annotation>
			<xs:documentation>沉迷配置</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="baseID" type="xs:int">
					<xs:annotation>
						<xs:documentation>ID</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="duration" type="xs:int">
					<xs:annotation>
						<xs:documentation>沉迷所属时间段(分钟)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="isTired" type="xs:int">
					<xs:annotation>
						<xs:documentation>是否到疲劳时间</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="durationStr" type="xs:string">
					<xs:annotation>
						<xs:documentation>沉迷通知内容</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="notifyDuration" type="xs:int">
					<xs:annotation>
						<xs:documentation>通知间隔(分钟)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="income" type="xs:int">
					<xs:annotation>
						<xs:documentation>收益影响比例</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="needOffline" type="xs:int">
					<xs:annotation>
						<xs:documentation>是否强制下线</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AddictionList">
		<xs:annotation>
			<xs:documentation>防沉迷列表</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="addictionSwitch" type="xs:int">
					<xs:annotation>
						<xs:documentation>防沉迷检查开关</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="minorNotify" type="xs:string">
					<xs:annotation>
						<xs:documentation>未成年通知</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="tireNotify" type="xs:string">
					<xs:annotation>
						<xs:documentation>疲劳时间登录通知</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Addiction" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>沉迷</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yoshikun/Mobile/Test/Resources/data/Addiction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by MES (MSM) -->
<AddictionList xsi:noNamespaceSchemaLocation="Addiction.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<addictionSwitch>0</addictionSwitch>
	<minorNotify>由于您的账号尚未进行身份验证，因此将被纳入防沉迷系统。游戏时间累计超过3小时后将被强制离线，您休息5小时后可重新登录。</minorNotify>
	<tireNotify>您当前已经进入疲劳游戏时间，请您合理安排游戏时间。</tireNotify>
	<Addiction>
		<baseID>1</baseID>
		<duration>60</duration>
		<isTired>0</isTired>
		<durationStr>您已累计在线1小时，请抽空起身活动一下身体，并让眼部得到适当的休息。为了您的健康请合理安排游戏时间。</durationStr>
		<notifyDuration>60</notifyDuration>
		<income>100</income>
		<needOffline>0</needOffline>
	</Addiction>
	<Addiction>
		<baseID>2</baseID>
		<duration>120</duration>
		<isTired>0</isTired>
		<durationStr>您已累计在线2小时，请抽空起身活动一下身体，并让眼部得到适当的休息。为了您的健康请合理安排游戏时间。</durationStr>
		<notifyDuration>60</notifyDuration>
		<income>100</income>
		<needOffline>0</needOffline>
	</Addiction>
	<Addiction>
		<baseID>3</baseID>
		<duration>180</duration>
		<isTired>1</isTired>
		<durationStr>您当前累计游戏时间已超过3小时，即将被强制离线，您休息5小时后可重新登录。亚特兰蒂斯大陆的大家都很牵挂您的身体，请务必合理安排休息时间。</durationStr>
		<notifyDuration>59</notifyDuration>
		<income>0</income>
		<needOffline>1</needOffline>
	</Addiction>
</AddictionList>
